Revert "Reland "Reland "siso: Run Android proguard actions remotely"""
This reverts commit 3cf76934f97d794a9d4b5faa915a13c42044c606.

Reason for revert: Speculative. See b/376450723

Original change's description:
> Reland "Reland "siso: Run Android proguard actions remotely""
>
> This reverts commit 89612ce7df4f26649a55aa0fa124e9050bebf7ab.
>
> Reason for revert: siso ninja -t cleandead removed jar output files
> that aren't specified in the build graph.
> But we changed the Siso's behavior to retain them for now.
>
> Original change's description:
> > Revert "Reland "siso: Run Android proguard actions remotely""
> >
> > This reverts commit 76ad7cb717183d97047dd491c097142104566395.
> >
> > Reason for revert: Trybots are failing:
> >
> > FileNotFoundError: [Errno 2] No such file or directory: 'obj/chrome/android/trichrome_chrome_64_bundle__dev_ui_bundle_module/trichrome_chrome_64_bundle__dev_ui_bundle_module.r8dex.jar'
> >
> > E.g.: https://ci.chromium.org/ui/p/chromium/builders/try/android-x64-rel/219474/overview
> >
> > Original change's description:
> > > Reland "siso: Run Android proguard actions remotely"
> > >
> > > This reverts commit 45eafaea49c2b3401c7c051b74fa2ef9f6a38608.
> > >
> > > Reason for revert: There was a bug in the command line parsing logic.
> > > https://crrev.com/c/5881697/1..5
> > >
> > > So, some inputs weren't included in the remote executions.
> > > However, some proguard actions could complete even without some missing
> > > files(?), which ended up with producing invalid outputs.
> > > e.g. stale outputs
> > >
> > > Original change's description:
> > > > Revert "siso: Run Android proguard actions remotely"
> > > >
> > > > This reverts commit 392decb1ca6bbc604cebfacab6bb593fbc093f26.
> > > >
> > > > Reason for revert: Suspect it is causing inaccurate android-binary-size results
> > > >
> > > > Original change's description:
> > > > > siso: Run Android proguard actions remotely
> > > > >
> > > > > Each proguard action takes about 4GB of memory, which runs at
> > > > > the last link phase. This sometimes makes bot builds fail for OOM or
> > > > > slow.
> > > > > This CL offloads proguard actions to RBE workers.
> > > > >
> > > > > Bug: 355704916
> > > > > Change-Id: Ia63bd5884817c91dd186ab36d8d3cdd4bc3378a7
> > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5872370
> > > > > Auto-Submit: Junji Watanabe <jwata@google.com>
> > > > > Commit-Queue: Junji Watanabe <jwata@google.com>
> > > > > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > > > > Reviewed-by: Philipp Wollermann <philwo@google.com>
> > > > > Cr-Commit-Position: refs/heads/main@{#1358021}
> > > >
> > > > Bug: 355704916, 369178106
> > > > Change-Id: I75a245f7ae6f235282537d4f4d4ce550d6964051
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5882620
> > > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > > Reviewed-by: Fumitoshi Ukai <ukai@google.com>
> > > > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > > > Cr-Commit-Position: refs/heads/main@{#1359124}
> > >
> > > Bug: 355704916, 369178106
> > > Change-Id: I293f7f460c89e4d81b8615ec754d73e4c3342fc3
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5881697
> > > Commit-Queue: Junji Watanabe <jwata@google.com>
> > > Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> > > Reviewed-by: Fumitoshi Ukai <ukai@google.com>
> > > Cr-Commit-Position: refs/heads/main@{#1364080}
> >
> > Bug: 355704916, 369178106
> > Change-Id: I85e5bdace04c4e834274b45e9e36ffe5aface56e
> > No-Presubmit: true
> > No-Tree-Checks: true
> > No-Try: true
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5905233
> > Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > Cr-Commit-Position: refs/heads/main@{#1364228}
>
> Bug: 355704916, 369178106
> Change-Id: I172acb3950436c1d56e9600ae8e7d46b709e9454
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5907591
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Fumitoshi Ukai <ukai@google.com>
> Cr-Commit-Position: refs/heads/main@{#1375658}

Bug: 355704916, 369178106, 376450723
Change-Id: Ia90aa8d443145a3291c6b56dd6699cc5792c57d8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5978881
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1375899}
NOKEYCHECK=True
GitOrigin-RevId: bab1d0abcbf506c1c217db304b885aea922b9ffc