siso: Support remote tools/resources/generate_resource_allowlist.py
This CL fixes the following error:
https://ci.chromium.org/ui/p/chromium/builders/try/android-code-coverage-native/43/overview
>  python3 ../../tools/resources/generate_resource_allowlist.py -o gen/android_webview/system_webview_pak_allowlist.txt lib.unstripped/libsystem_webview_pak_allowlist_inputs.so
...
FileNotFoundError: [Errno 2] No such file or directory: 'obj/components/component_updater/android/libembedded_component_loader.a'

With this CL, the error doesn't happen.
https://ci.chromium.org/ui/p/chromium/builders/try/android-code-coverage/62/overview

When remote linking is enabled, the bot doesn't download .o, .a
by default, which is problematic for `tools/resources/generate_resource_allowlist.py` because it needs to
read them.
Instead of downloading .o, .a, this CL runs generate_resource_allowlist.py remotely so that the bot doesn't need to download the intermediate files.

This CL is noop for Android builders until remote linking is enabled
by https://crrev.com/c/5912602.

Bug: 372371165
Fixed: 372371165
Change-Id: I3b3460e148dacecc19d57d5b22cb9b3ffdd94383
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5918349
Auto-Submit: Junji Watanabe <jwata@google.com>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Junji Watanabe <jwata@google.com>
Cr-Commit-Position: refs/heads/main@{#1366573}
NOKEYCHECK=True
GitOrigin-RevId: d9d333cda572662f547e3aded4d338ab09d5a31b